### PR TITLE
fix URL related Errors

### PR DESCRIPTION
**Pull request by webdesserts**
When I try to initialize a new WebDB instance in the browser I get the following error:

```
Unhandled Rejection (ReferenceError): URL is not defined
```

The error points to [this line](https://github.com/beakerbrowser/webdb/blob/master/lib/util.js#L4). Adding an explicit reference to `window` at the beginning seems to fix the issue.

### CODE REVIEW

**Comment by webdesserts** [comment]
There may be a few other `URL` related issues. I'll see if I can patch them as well. [This line specifically](https://github.com/beakerbrowser/webdb/blob/master/lib/table.js#L102) is causing hell now.

**Comment by webdesserts** [comment]
Alright, I'll let you know if I run into any more, but that's it so far.

**Comment by pfrazee** [comment]
👍  Awesome, thanks

**Comment by pfrazee** [comment]
Published 2.1.2

**Pull request merged**
