### PR TITLE
Enhancement/iss23

### LINKED ISSUE #23: Emit some information when validation fails
I've been playing around with this trying to learn it (very exciting!!!), and was really struggling to get any records to show up in my test DB. As I drilled into things, I realized that I had a copy/paste error in my code:

```
await db.define('people', {
      // validate required attributes before indexing
      validate(record) {
        assert(record.name && typeof record.name === 'string')
        assert(record.bio && typeof record.bio === 'string')
        return true
      },
    ...
```

`assert` is not defined and thus a Reference Error was getting thrown, but the try/catch block in `indexer.js` just sets `isValid = false;` and ditches the error, so I had no idea what the problem was. What are your thoughts of throwing the error if it catches one? It'll be a simple enough fix, so you may see a PR from me later 😬 .

Here's the snippet from `indexer.js` I'm talking about:

```
async function readAndIndexFile (db, archive, filepath, version=false) {
     ...
    // index on the first matching table
    for (var i = 0; i < tables.length; i++) {
      let table = tables[i]
      if (table.isRecordFile(filepath)) {
        // validate
        let isValid = true
        if (table.schema.validate) {
          try { isValid = table.schema.validate(record) }
          catch (e) { isValid = false } <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        }
```

### PR DESCRIPTION
**Pull request by jakofranko**
Fixes #23

### CODE REVIEW

**Comment by pfrazee** [comment]
Thanks for the PR! Rather than calling `onFailInitialIndex` we should add a 'validation-failed' error to WebDB, and emit that.

**Comment by jakofranko** [comment]
Alrighty sounds good, I'll take a look at that tomorrow me thinks. Should I wrap the new `validation-failed` error in any kind of helper function a la `onFailInitialIndex` or emit it directly?

**Comment by pfrazee** [comment]
I think just emit it directly. A failed validation can happen because somebody else wrote a bad file to their archive, so it's often something you want to ignore.

**Comment by jakofranko** [comment]
Sounds good.

**Comment by jakofranko** [comment]
How's that?

**Comment by pfrazee** [comment]
> I noticed that this won't get emitted unless an error gets thrown; otherwise, isValid will just evaluate to false, so really you'll only see it if your validator is broken...could be missing something though.

Hmm. The reason it catches errors, right now, is so that validation code can use `assert()`. I think we either need to treat thrown errors as errors in code, or we need to emit the event when the function returns false.

**Comment by jakofranko** [comment]
Treating thrown errors as errors in code makes the most sense to me. If a record isn't valid, it shouldn't stop my program. If my _validator_ is broken, my program _should_ stop because I need to fix my validator. If that's the case, then the logic as it stands right now is correct; `validation-failed` means just that: couldn't validate because of a thrown error. A successful validation can still return `false`: it successfully validated that a record was not valid.

**Comment by jakofranko** [comment]
Heh heh, the verbiage gets a bit wonky. Anyways that's just my coding sensibilities, I'm happy to defer to your good judgment in the matter however.

**Comment by pfrazee** [comment]
I think that's probably wise. Let's go with your plan.

**Comment by jakofranko** [comment]
Excellent. Do I need to add anything else or does it look ok now?

**Comment by pfrazee** [comment]
I think actually we should reapproach it. If we're treating a thrown exception as a programming error, then we shouldnt emit an event or log to `debug()`. We should just `console.error()` the exception, and set `isValid = false` so that the indexer can continue gracefully.

**Comment by jakofranko** [comment]
works for me. Sorry, was out of the country this past week for work, I'll try to do this tonight so we can close this out!

**Comment by pfrazee** [comment]
Thanks for slogging through this with me! Didn't end up being a big change in the end, but it's a good change.

**Comment by pfrazee** [comment]
Published `4.3.1`

**Pull request merged**
